version: '3.9'
services:
  aws:
    image: hanvitha/pythonaws
    ports:
      - "80:80"
    deploy:
      replicas: 3
  devops:
    image: hanvitha/pythondevops
    ports:
      - "81:80"
    deploy:
      replicas: 3
  linux:
    image: hanvitha/pythonlinux
    ports:
      - "82:80"
    deploy:
      replicas: 3
